[package]
name = "omnara_voxel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }

# ⚡ إعدادات تقليص حجم الملف وتسريع الأداء للهواتف ⚡
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
